src/MyApp/ApBundle/Entity/Image.php
<?php
namespace MyApp\ApBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks ()
 */
class Image
{
    /**
   * @ORM\Column(name="id", type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  private $id;
 
  /**
   * @ORM\Column(name="url", type="string", length=255)
   */
  private $url;
 
  /**
   * @ORM\Column(name="alt", type="string", length=255)
   */
  private $alt;
 
  private $file;
  
  private $tempFilename;
  
  public function getFile() {
        return $this->file;
    }
 
public function setFile( $file) {
        $this->file = $file;
    } 

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;
    
        return $this;
    }

    /**
     * Get url
     *
     * @return string 
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;
    
        return $this;
    }

    /**
     * Get alt
     *
     * @return string 
     */
    public function getAlt()
    {
        return $this->alt;
    }
 
/**
   * @ORM\PrePersist()
   * @ORM\PreUpdate()
   */
  public function preUpload()
  {
    // Si jamais il n'y a pas de fichier (champ facultatif)
    if (null === $this->file) {
      return;
    }
 
    // Le nom du fichier est son id, on doit juste stocker également son extension
    // Pour faire propre, on devrait renommer cet attribut en "extension", plutôt que "url"
    $this->url = $this->file->guessExtension();
 
    // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
    $this->alt = $this->file->getClientOriginalName();
  }
 
  /**
   * @ORM\PostPersist()
   * @ORM\PostUpdate()
   */
  public function upload()
  {
    // Si jamais il n'y a pas de fichier (champ facultatif)
    if (null === $this->file) {
      return;
    }
 
    // Si on avait un ancien fichier, on le supprime
    if (null !== $this->tempFilename) {
      $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
      if (file_exists($oldFile)) {
        unlink($oldFile);
      }
    }
 
    // On déplace le fichier envoyé dans le répertoire de notre choix
    $this->file->move(
      $this->getUploadRootDir(), // Le répertoire de destination
      $this->id.'.'.$this->url   // Le nom du fichier à créer, ici "id.extension"
    );
  }
 
  /**
   * @ORM\PreRemove()
   */
  public function preRemoveUpload()
  {
    // On sauvegarde temporairement le nom du fichier car il dépend de l'id
    $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
  }
 
  /**
   * @ORM\PostRemove()
   */
  public function removeUpload()
  {
    // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
    if (file_exists($this->tempFilename)) {
      // On supprime le fichier
      unlink($this->tempFilename);
    }
  }
 
  public function getUploadDir()
  {
    // On retourne le chemin relatif vers l'image pour un navigateur
    return 'uploads/img';
  }
 
  protected function getUploadRootDir()
  {
    // On retourne le chemin relatif vers l'image pour notre code PHP
    return __DIR__.'/../../../../web/'.$this->getUploadDir();
  }
  
    public function getWebPath()
  {
    return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
  }
    
}

src/MyApp/ApBundle/Controller/EstimationController.php
<?php

namespace MyApp\ApBundle\Controller;

use Symfony\Component\DependencyInjection\ContainerAware;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use MyApp\ApBundle\Entity\Client;
use MyApp\ApBundle\Entity\Service;
use MyApp\ApBundle\Entity\Note;
use MyApp\ApBundle\Form\NoteForm;
use MyApp\ApBundle\Entity\City;
use MyApp\ApBundle\Entity\Contrat;
use MyApp\ApBundle\Entity\DateTable;
use MyApp\ApBundle\Entity\ClientService;
use MyApp\ApBundle\Form\ClientForm;
use MyApp\ApBundle\Form\ClientEtatForm;
use Ivory\GoogleMapBundle\Model\MapTypeId;
use Ivory\GoogleMapBundle\Model\Overlays\Animation;

use MyApp\ApBundle\Form\EstimationForm;

class EstimationController extends ContainerAware
{

  public function voirClientAction($id) 
    { 
      $em = $this->container->get('doctrine')->getEntityManager();
      $client = $em->find('MyAppApBundle:Client', $id);




             $query = $em->createQuery('SELECT a.city FROM MyAppApBundle:Client c JOIN c.city a 
     WHERE c.id = :id')->setParameter('id', $id);
        $city = $query->getResult();

      $geocoder = $this->container->get('ivory_google_map.geocoder');
      $test= $client ->getNumber()." ".$client ->getStreet()." ".$city[0]['city']." ".$client -> getPc();
      $response = $geocoder->geocode($test);

      $map = $this->container->get('ivory_google_map.map');
      
      // Requests the ivory google map marker service
        $marker = $this->container->get('ivory_google_map.marker');
      
      // Sets your marker animation
        $marker->setAnimation('bounce');

      foreach($response->getResults() as $result)
{
    // Request the google map merker service
    $marker = $this->container->get('ivory_google_map.marker');

    // Position the marker
    $marker->setPosition($result->getGeometry()->getLocation());

    // Add the marker to the map
    $map->addMarker($marker);
}
      $contrats = new Contrat;
      

    
    $clientServices= $em->getRepository('MyAppApBundle:ClientService')->findByClient($id);
           


        
        
                $message='';
                $conn = $this->container->get('database_connection');
        $sql=('SELECT c.created, c.numero, c.id, c.date, sum(cs.prix) as prix, group_concat( s.type ) AS service
FROM Contrat c
LEFT JOIN contrat_clientservice t ON t.contrat_id=c.id
LEFT JOIN ClientService cs ON t.clientservice_id = cs.id
LEFT JOIN Service s ON s.id = cs.service_id
LEFT JOIN Client d ON d.id = c.client_id
WHERE d.id = :clientid
GROUP BY c.id');
 $clientservicestest = $conn->prepare($sql);
$clientservicestest->bindValue("clientid", $client->getId());
$clientservicestest->execute();        
    if (!$client) 
    {
        throw new NotFoundHttpException("service non trouvé");
    }         
        $note = new Note();
        $formNote = $this->container->get('form.factory')->create(new NoteForm(),$note);
        $request = $this->container->get('request');
        if ($request->getMethod() == 'POST') 
        {
        $formNote->bind($request);
                    
            if ($formNote->isValid()) 
                {   
                    $note->setClient($client);
                    $note ->setType('Pap');
                    $em->persist($note);
                    $em->flush();
                    $message='Note ajouté avec succès !';
                    
                    
                }
       
        }
         
          $notes= $em->getRepository('MyAppApBundle:Note')->findByClient($id);
      
         
         
    return $this->container->get('templating')->renderResponse('MyAppApBundle:Estimation:voir.html.twig', array(
    'client' => $client,
    'notes' => $notes,
    'message' => $message,
    'clientServices' => $clientServices,
    'formNote' => $formNote->createView(),
    'response' => $response,
    'map' => $map,
    'clientservicestest' => $clientservicestest,

    ));
    } 
     
  public function voirServiceAction($id) 
    { 
    $em = $this->container->get('doctrine')->getEntityManager();
    $client = $em->find('MyAppApBundle:Client', $id);
         $message = '';
    
    if (!$client) 
    {
        throw new NotFoundHttpException("service non trouvé");
    }
        $form = $this->container->get('form.factory')->create(new EtatForm(), $client);
        $request = $this->container->get('request');
        if ($request->getMethod() == 'POST') 
        {
            $form->bind($request);
                    
            if ($form->isValid()) 
                {       
                    $em = $this->container->get('doctrine')->getEntityManager();
                    $em->persist($client);
                    $em->flush();
                    $message='Etat ajouté avec succès !';
                }
                return new RedirectResponse($this->container->get('router')->generate('myapp_client_lister'));
         }
    return $this->container->get('templating')->renderResponse('MyAppApBundle:Client:voir.html.twig', array(
    'client' => $client, 
    'message' => $message, 
    ));
    } 
       public function suivantAction($id)
    {
        $em = $this->container->get('doctrine')->getEntityManager();
          $request = $this->container->get('request');
          $param = $request->get('param');
          $etat = $request->get('etat');
        $client = $em->getRepository('MyAppApBundle:Client')
                         ->find($id);
                 if($etat!=null){
      
   
                 
                                   $liste_articles = $em->getRepository('MyAppApBundle:Client')
                         ->myFindNextClientEtat($etat);
           
}
else{
    $liste_articles = $em->getRepository('MyAppApBundle:Client')
                         ->myFindNextClient();
}
 
          $id = intval($id);
                 foreach ($liste_articles as $article){
                     $test= $article->getId();
                     if($test == $id){
                         if($param == 'Next'){
                         $idPrev = current($liste_articles);
                         
                         $idPrev = intval($idPrev ->getId());
                         }
                        elseif($param === 'Prev'){
                            $idPrev = prev($liste_articles);
                            $current_index = array_search( $idPrev,$liste_articles);
                            
                         $current_index = $current_index - 1;
                         if($current_index < 0){
                             echo 'rien avamt!';
                             
                         }
          $test = $liste_articles[$current_index];
                        $idPrev = intval($test ->getId());

                       

                         }
                         
                     }
                         
                         
                 }     
                     
                 
 
    
    return new RedirectResponse($this->container->get('router')->generate('myapp_estimation_voirClient', array(
    'id' => $idPrev, 
    )));
    }
}

src/MyApp/ApBundle/Resources/views/Estimation/ajouter.html.twig
{% extends 'MyAppApBundle::layout.html.twig' %}
{% block title %}{% endblock %}

{% block content %}
{% if message %}
<p>{{ message }}</p>
{% endif %}
<h6>Ajouter un service à: {{ client.prenom|capitalize }} {{ client.nom|upper }} </h6>
<form action="" method="post" {{ form_enctype(form) }}>
    {{ form_widget(form) }}
    <input type="image" src="{{ asset('bundles/myappap/images/add.png') }}"/>
</form>


{% endblock %}

src/MyApp/ApBundle/Resources/views/Estimation/voir.html.twig
{% extends 'MyAppApBundle::layout.html.twig' %}
{% block title %}
    Fiche client:
{% endblock %}
{% block previous %}
<a href="{{ path('myapp_estimation_suivant', { 'id': client.id, 'client': client, 'param':'Prev' }) }}"> Précèdent</a>
{% endblock %}
{% block next %}
<a href="{{ path('myapp_estimation_suivant', { 'id': client.id, 'client': client, 'param':'Next' }) }}"> Suivant</a>
{% endblock %}
{% block recherche %}

                         <a href="{{ path('myapp_client_modifier', { 'id': client.id }) }}">{{ client.nom|upper }} {{ client.prenom|capitalize }}</a>
                        <a href="{{ path('myapp_estimation_suivant', { 'id': client.id, 'client': client, 'etat': client.etat, 'param':'Prev' }) }}" class="icon-arrow-left-2"></a>
                        <span>État: {{ client.etat }}</span>
                        <a href="{{ path('myapp_estimation_suivant', { 'id': client.id, 'etat': client.etat, 'param':'Next' }) }}" class="icon-arrow-right-2"></a>
{% endblock %}



{% block principalNote %}   


                    <div class="right-map">
<table id="map">
            <tr>
                <td>
                    {{ google_map_container(map) }}
                    {{ google_map_js(map) }}
                </td>
            </tr>
            </table>
            </div>





<div class= "info-client">

            <div class="client">
 <address>
  {{ client.number }} {{ client.street }}<br>
  {{ client.city.city|capitalize }}, {{ client.pc|upper }}<br>
 </address>
{% for p in client.phones %}
    {{ p.phoneType.phoneType|capitalize }}: {{ p.phone }}
    <br>
{% else %}
        Aucun Téléphone.
{% endfor %}
<br>
<a href="mailto:{{ client.email }}">{{ client.email }}</a>
</address>

<h6>Service demandés: {{ client.service.type|capitalize }}</h6>                        
    <h6>Créé par: {{ client.user|capitalize }} le {{ client.dateTable.date|date('d M y') }}</h6>
    </div>
    <div id="note">
    <pre id="note">Note</pre>


<form action="{{ path('myapp_estimation_voirClient', {'id' : client.id}) }}" method="post">
    {{ form_widget(formNote) }}
    <input type="submit" value="Ajouter" />
</form>
<div class="loading"></div>
<div id="resultats_notes"> 
    {% include 'MyAppApBundle:Note:liste.html.twig' with {'notes' : notes}  %}
</div>
</div>              

{% endblock %}
    
{% block right %}
<div id="services">
  <h2>Services<a href="{{ path('myapp_estimation_creerService', { 'id': client.id }, { 'map': map }) }}"> <img src="{{ asset('bundles/myappap/images/add.png') }}" title="Ajouter Service"/></a></h2>

{% if clientServices %}
<table>
{% for s in clientServices %}

        <tr>
            <td><span class="dateSpan"><b>{{ s.created|date('d/m/y') }}</b></span></td>
            <td>{{ s.service.type }}</td>
            <td>{{ s.prix|number_format(2, ',', '.') }}$</td>
            <td>{{ s.note|capitalize }}</td> 
            <td><a href="{{ path('myapp_service_supprimerService', { 'idd': s.id,'id': client.id  }) }}"><img src="{{ asset('bundles/myappap/images/cross.png') }}" title="Supprimer service"/></a></td>
          
        {% if s.image.webpath is defined %}
        <td><span class="icone"><img src="{{ asset(s.image.webPath) }}" alt="{{ s.image.alt }}" class="img-polaroid"  width="100px" height="100px" /></span></td>
         {% endif %}

        </tr>
{% endfor %}
</table>
{% else %}
Aucun Services trouvés
 {% endif %}
        

             <h2>Contrats<a href="{{ path('myapp_contrat_ajouter', { 'id': client.id }) }}"> <img src="{{ asset('bundles/myappap/images/add.png') }}" title="Ajouter Contrat"/></a></h2>

       {% if clientservicestest %}
<table id="tbestimation">
{% for co in clientservicestest %}
        <tr>
            <td><span class="dateSpan"><b>{{ co.created|date('d/m/y') }}:</b></span></td>
            <td>{{ co.numero }}</td>
            <td>{{ co.service }}</td>
            <td>{{ co.prix }}$</td>

            <td><a href="{{ path('myapp_contrat_voir', { 'id': co.id }) }}"><img src="{{ asset('bundles/myappap/images/binoculars.png') }}" alt="Stats"/></a></td></td>
            {% if co.date != null %}
                <td>{{ co.date|date('d M y') }}</td
            {% else %}
                <td>N/A</td>
            {% endif %}
         </tr>       
{% else %}
    <tr>
        <td>Aucunes contrats trouvées</td>
    </tr>
{% endfor %}
    </table> 
{% endif %}   
</div>
                </div>
            </div><!-- /main -->
        </div><!-- /container -->

        {% endblock %}